"""up

Revision ID: 429ad669c0d5
Revises: ffb95ef098d0
Create Date: 2024-01-21 17:38:00.860201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429ad669c0d5'
down_revision = 'ffb95ef098d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_phone_number', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_phone_number'], ['user.phone_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recurring_date')
    # ### end Alembic commands ###
