"""Add reminder settings to User model

Revision ID: 66791e0c6257
Revises: 429ad669c0d5
Create Date: 2024-01-22 20:33:17.086709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66791e0c6257'
down_revision = '429ad669c0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remind_7_days', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remind_3_days', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remind_1_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('remind_on_day', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('remind_on_day')
        batch_op.drop_column('remind_1_day')
        batch_op.drop_column('remind_3_days')
        batch_op.drop_column('remind_7_days')

    # ### end Alembic commands ###
